#!/usr/bin/env bash

# Don't use "set -e" because markdown needs to keep going on all files
set -u -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

if ! command -v terraform-docs > /dev/null; then
  echo "terraform-docs is missing."
  exit 1
fi

terraform-docs markdown . > README.md
{
  echo "<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->"
  cat README.md
  echo "<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->"
} >> TMP_README.md
mv TMP_README.md README.md
